### PR TITLE
update angular 18

### LINKED ISSUE #2241: Support for Angular 18
Use angular 18 in angular-shepherd

### PR DESCRIPTION
**Pull request by bastienmoulia**
Fix #2241

### CODE REVIEW

**Comment by phhbr** [comment]
LGTM

**Comment by phhbr** [comment]
Can you take a look @RobbieTheWagner? Thanks a lot 👍

**Review by RobbieTheWagner — APPROVED** [review]

**Comment by RobbieTheWagner** [comment]
@bastienmoulia looks like we need to fix some CI issues with volta before we can merge this. Would you be interested in taking that on?

**Comment by bastienmoulia** [comment]
> @bastienmoulia looks like we need to fix some CI issues with volta before we can merge this. Would you be interested in taking that on?

I don't know what is Volta... I maybe will have some time to look at it but not sure.

**Comment by chuckcarpenter** [comment]
@bastienmoulia I fixed the volta issue and tried to version lock CLI, but schematics requires a < 18 of CLI to work. I think you'll need to update that and the other eslint packages for v18. e.g., 

```
"peerDependencies": {
    "@angular/cli": ">= 17.0.0 < 18.0.0"
  },
  ```

**Comment by bastienmoulia** [comment]
> @bastienmoulia I fixed the volta issue and tried to version lock CLI, but schematics requires a < 18 of CLI to work. I think you'll need to update that and the other eslint packages for v18. e.g., of the problem in schematics package.json
> 
> ```
> "peerDependencies": {
>     "@angular/cli": ">= 17.0.0 < 18.0.0"
>   },
> ```
Done

**Comment by chuckcarpenter** [comment]
@RobbieTheWagner do you just release this from your local then?

**Comment by VilleFTW** [comment]
Hi @RobbieTheWagner ,

Could you please do a new release with support for v18 on npm?

**Comment by pathrom** [comment]
> Hi @RobbieTheWagner ,
> 
> Could you please do a new release with support for v18 on npm?

Please

**Comment by RobbieTheWagner** [comment]
It has been released now

**Pull request merged**
